### ISSUE TITLE
Error message using teams_scraper.py

### ISSUE THREAD

**Issue by elrobak** [vaastav/Fantasy-Premier-League#19]
Just had an issue start today when attempting to pull player stats with teams_scraper.py. 

The error message is:

Traceback (most recent call last):
  File "teams_scraper.py", line 26, in <module>
    main()
  File "teams_scraper.py", line 20, in main
    parse_entry_history(summary, output_folder)
  File "D:\python\fpl\parsers.py", line 56, in parse_entry_history
    chips_df = pd.DataFrame.from_records(data["chips"])
KeyError: 'chips'

I've made no changes to the system/files from last week when it was working fine, I'm on the site and able to access the api endpoints so I don't think it's a "logged" in issue. Could it be that the gameweek hasn't finished yet?

**Comment by vaastav** [comment]
teams_scraper.py is for pulling data for your own team or some other team using the team ID.
global_scraper.py is for pulling player data.

**Comment by elrobak** [comment]
Sorry, when I said player stats I meant people running teams in my league rather than footballers, should have been more clear!

**Comment by elrobak** [comment]
185715 is my own but it's happening on every team_id I put in.

**Comment by vaastav** [comment]
Hmm, i just tested it out and I seem to be able to download the data perfectly. Have you pulled the repo updates recently? FPL did changes to the API last week that broke everything. I uploaded a fix and it seems like that is the issue you are suffering with.

Can you please do a git pull and see if the updated changes also have the same issue?

**Comment by elrobak** [comment]
I've just deleted the folder and downloaded a new copy and everything has started working again.

Absolutely baffling but resolved, thank you.

**Comment by vaastav** [comment]
So, the issue was indeed the FPL updating their API. 
I updated the scripts to change that so you had to update the repo.
You had to delete and download the repo to basically download this change. It's essentially updating the version of any software you use (Like updating Windows 7 to Windows 8 albeit on a smaller scale).

Glad everything works now! Cheers.

You might need to update again in a couple of week when I add the gw picks data for each team as well (Basically what were the players for that specific team in each gw and who was captained etc.)
