### ISSUE TITLE
Add GitHub Actions workflow

### ISSUE THREAD

**Issue by ravgeetdhillon** [vaastav/Fantasy-Premier-League#32]
Instead of manually pushing the data before each game week, let us automate the process using GitHub Actions.

**Comment by ravgeetdhillon** [comment]
@vaastav Hey man. Since that workflow run efficiently, I suggest you to uncomment the `on schedule` code and comment out the `on push`.

Also if you could acknowledge my contribution in **Acknowledgment** section on README, that would be really appreciable.

**Comment by vaastav** [comment]
Thanks, will do!
Would I have to update the schedule for the new season next August or can it be auto-generated?

**Comment by ravgeetdhillon** [comment]
No. You will have to update the schedule yourself. But I can write a script for you which will give a cron list of the schedule when the next season starts.

**Comment by vaastav** [comment]
Yes, that would be awesome.
Additionally if you were writing that script then would it be possible for you to generate
the cron list for 1 day after the end of the gameweek instead of 2 days before the gameweek. That would allow for data to be updated very quickly.

I have added your name in the acknowledgement section. Again, thanks for the contribution.

**Comment by ravgeetdhillon** [comment]
Yes, you are right. I will try to implement the above logic by the weekend. Thanks for the acknowledgment.
