### ISSUE TITLE
Duplicate data in gameweek files

### ISSUE THREAD

**Issue by randomm** [vaastav/Fantasy-Premier-League#4]
Hi,

I noticed that sometimes the gameweek files contain duplicates of players. Looking at the data more carefully the fixture is not the same, so does that mean that for some reason two games feature under a single gameweek?

https://v.usetapes.com/c8D7X9Yv05

This is from the gw37.csv file from 2017-2018 season.

Thanks ever so much for your work! I'm working on an LSTM network based solution to suggest substitutions and captains.

**Comment by vaastav** [comment]
The reason for that is the fact that in a single gameweek, a team might play 2 different fixtures, one of which is the regular fixture and the other is a fixture that got rescheduled earlier in the season due to bad weather or cup competitions. This is what is colloquially referred to as double gameweek (2 fixtures 1 gameweek).

Last season, gw37 was a massive double gameweek where multiple teams had 2 fixtures. If memory serves me right then gw34 was also a double gameweek.

An LSTM network sounds cool but I don't think substitutions are useful considering you can't make subs during a gameweek. Transfers + Captains would be the right kind of predictions. 
Just to give my opinion regarding this, using a Ranker will most likely be the better choice instead of a classifier as classifier would give you a yes/no answer whereas a Ranker would give you more information regarding how players compare with each other.
Once you have a post published regarding that or some kind of preliminary work, please let me know so that I can add you to the README.

**Comment by vaastav** [comment]
Closing this issue!
